# data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.data-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/data
---
# dashboard
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.dashboard-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/dashboard
---
# provisioning
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.provisioning-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/provisioning
