# data
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.grafana.data-claim # Sets name of PV
  labels:
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
  volumeName: monitoring.grafana.data-volume
---
# dashboard
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.grafana.dashboard-claim # Sets name of PV
  labels:
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Mi # Sets volume size
  volumeName: monitoring.grafana.dashboard-volume
---
# provisioning
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.grafana.provisioning-claim # Sets name of PV
  labels:
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Mi # Sets volume size
  volumeName: monitoring.grafana.provisioning-volume
---
# ini
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.grafana.ini-claim # Sets name of PV
  labels:
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 1Mi # Sets volume size
  volumeName: monitoring.grafana.ini-volume
