apiVersion: 1

datasources:
- name: Jaeger
  type: jaeger
  access: proxy
  url: http://monitoring:16686
  allowUiUpdates: true
  jsonData:
    tracesToLogs:
      lokiSearch: false
  version: 1
  uid: AXGOQHa4k
  editable: true