version: "3.9"

services:
  collector:
    build:
      context: ./fluentd
      dockerfile: Dockerfile.collector
    deploy:
      resources:
        limits:
          memory: '150M'

    profiles:
      - collector
      - all
    volumes:
      - ./fluentd:/usr/src/app
      - /sys/fs/cgroup:/log/resources
      - /var/lib/docker/containers/:/log/containers
      - ../WebHistory/backend/assets/fluentd/:/config/web-history/
      - ../WebHistory/bin/logs/:/log/web-history/
    networks:
      - default
    environment:
      - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2

    command: fluentd -c config.conf
    # command: tail -f /dev/null
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile.db
    deploy:
      resources:
        limits:
          memory: '100M'
      restart_policy:
        condition: on-failure
    profiles:
      - db
      - all
    env_file:
      - ./postgres/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  visualize:
    build:
      context: ./grafana
      dockerfile: Dockerfile.visualize
    deploy:
      resources:
        limits:
          memory: '75M'

    profiles:
      - visualize
      - all
    networks:
      - router
      - default
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:

networks:
  router:
    driver: bridge
    name: router
  default:
