version: "3.9"

services:
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile.visualize
    deploy:
      resources:
        limits:
          memory: '150M'

    profiles:
      - grafana
      - all
    networks:
      - router
      - default
      - trace
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
  backup:
    image: alpine:latest
    deploy:
      resources:
        limits:
          memory: '10M'
    volumes:
      - grafana_data:/grafana_source
      - ./grafana/data:/grafana_dest
    profiles:
      - backup
  jaeger:
    image: jaegertracing/all-in-one:latest
    deploy:
      resources:
        limits:
          memory: '50M'
    hostname: monitoring
    ports:
      - 8000:16686
        #- 14268:14268
    networks:
      - trace
    profiles:
      - jaeger
  cadvisor:
    # image: gcr.io/cadvisor/cadvisor:latest
    image: gcr.io/cadvisor/cadvisor-arm64:v0.46.0
    deploy:
      resources:
        limits:
          memory: '150M'
    privileged: true
    volumes:
      - /:/roofs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - trace
    hostname: cadvisor
    profiles:
      - cadvisor
      - all
  prometheus:
    image: prom/prometheus
    deploy:
      resources:
        limits:
          memory: '250M'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - trace
    profiles:
      - prometheus
      - all

volumes:
  postgres_data:
  grafana_data:

networks:
  router:
    driver: bridge
    name: router
  default:
  trace:
    driver: bridge
    name: trace
