version: "3.9"

services:
  grafana:
    build:
      context: ./frontend/grafana
      dockerfile: Dockerfile.visualize
    deploy:
      resources:
        limits:
          memory: '150M'
    hostname: monitoring_grafana
    profiles:
      - frontend
      - all
    networks:
      - router
      - default
      - trace
    ports:
      - 3001:3000
    volumes:
      - ./frontend/grafana/provisioning:/etc/grafana/provisioning
      - ./frontend/grafana/dashboards:/etc/dashboards
      - grafana_data:/var/lib/grafana
  backup:
    image: alpine:latest
    deploy:
      resources:
        limits:
          memory: '10M'
    volumes:
      - grafana_data:/grafana_source
      - ./backup/grafana:/grafana_dest
    profiles:
      - backup
  jaeger:
    image: jaegertracing/all-in-one:latest
    deploy:
      resources:
        limits:
          memory: '50M'
    hostname: monitoring
    environment: 
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - ./ingesters/jaeger/badger:/badger
    ports:
      - 8000:16686
        #- 14268:14268
    networks:
      - trace
    profiles:
      - trace
      - ingester
      - all
  prometheus:
    image: prom/prometheus
    deploy:
      resources:
        limits:
          memory: '250M'
    volumes:
      - ./ingesters/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    networks:
      - trace
    profiles:
      - metrics
      - ingester
      - all
  temperature-collector:
    build:
      context: ./collectors/go-temperature-collector
    deploy:
      resources:
        limits:
          memory: '10M'
    profiles:
      - metrics
      - collector
      - all
    networks:
      - trace
  container-resource-collector:
    build:
      context: ./collectors/container-resource-collector
    deploy:
      resources:
        limits:
          memory: '10M'
    profiles:
      - metrics
      - collector
      - all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - trace
  loki:
    image: grafana/loki:latest
    hostname: monitoring_loki
    ports:
      - 3100:3100
    # command: -config.gile=/etc/loki/local-config.yaml
    volumes:
      # - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./ingesters/loki/storage:/loki
    profiles:
      - logs
      - ingester
      - all
    networks:
      - trace
  logs-collector:
    image: grafana/fluent-bit-plugin-loki
    networks:
      - trace
    volumes:
      - ./collectors/fluent-bit:/fluent-bit/etc/
    profiles:
      - logs
      - collector
      - all
    command: [
      "/fluent-bit/bin/fluent-bit",
      "-R",
      "/fluent-bit/etc/parsers.conf",
      "-e",
      "/fluent-bit/bin/out_grafana_loki.so",
      "-c",
      "/fluent-bit/etc/fluent-bit.conf"
    ]


volumes:
  postgres_data:
  grafana_data:

networks:
  router:
    driver: bridge
    name: router
  default:
  trace:
    driver: bridge
    name: trace
