version: "3.9"

services:
  collector:
    build:
      context: ./fluentd
      dockerfile: Dockerfile.collector
    deploy:
      resources:
        limits:
          memory: '150M'

    profiles:
      - collector
      - all
    volumes:
      - ./fluentd:/usr/src/app
      - /sys/fs/cgroup/system.slice:/log/resources
      - /var/lib/docker/containers/:/log/containers
      - ../WebHistory/backend/assets/fluentd/:/config/web-history/
      - ../BookSpider/backend/assets/fluentd/:/config/book-spider/
      - ../WebHistory/bin/logs/:/log/web-history/
      - ../BookSpider/bin/logs/:/log/book-spider/
    networks:
      - default
    environment:
      - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2

    command: fluentd -c config.conf
    # command: tail -f /dev/null
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile.db
    deploy:
      resources:
        limits:
          memory: '100M'
      restart_policy:
        condition: on-failure
    profiles:
      - db
      - all
    env_file:
      - ./postgres/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  visualize:
    build:
      context: ./grafana
      dockerfile: Dockerfile.visualize
    deploy:
      resources:
        limits:
          memory: '150M'

    profiles:
      - visualize
      - all
    networks:
      - router
      - default
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  backup:
    image: alpine:latest
    deploy:
      resources:
        limits:
          memory: '10M'
    volumes:
      - grafana_data:/grafana_source
      - ./grafana/data:/grafana_dest
    profiles:
      - backup
  jaeger:
    image: jaegertracing/all-in-one:latest
    deploy:
      resources:
        limits:
          memory: '50M'
    hostname: monitoring
    ports:
      - 3000:16686
      - 14268:14268
    networks:
      - trace
    profiles:
      - jaeger
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/roofs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    profiles:
      - cadvisor

volumes:
  postgres_data:
  grafana_data:

networks:
  router:
    driver: bridge
    name: router
  default:
  trace:
    driver: bridge
    name: trace