scrape_configs:
- job_name: device_temperature
  scrape_interval: 20s
  static_configs:
  - targets:
    - temperature-collector:8000
- job_name: container_resource
  scrape_interval: 20s
  static_configs:
  - targets:
    - container-resource-collector:8000 
