apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.fluent-bit.logs-volume
  labels:
    label: local
    app: fluent-bit
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /var/log
