apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring.loki  # Sets Deployment name
  namespace: default
  labels:
    app: loki
    project: monitoring
resources:
  - ./base/deployment.yml
  - ./base/service.yml
  - ./base/pv.yml
  - ./base/pvc.yml
  - ./base/ingress.yml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: monitoring.loki
      labelSelector: "app=loki,project=monitoring"
    path: ./patch/deployment.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: monitoring.loki
    path: ./patch/ingress.yml
