apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring.fluent-bit  # Sets Deployment name
  namespace: default
  labels:
    app: fluent-bit
    project: monitoring
resources:
  - ./base/deployment.yml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: monitoring.fluent-bit
      labelSelector: "app=fluent-bit,project=monitoring"
    path: ./patch/deployment.yml
configMapGenerator:
  - name: monitoring.fluent-bit.config-map
    files:
      - ./patch/fluent-bit.conf
      - ./patch/parsers.conf
