apiVersion: 1

datasources:
- name: PostgreSQL
  type: postgres
  url: monitoring_db_1:5432
  user: logging
  database: logging
  allowUiUpdates: true
  isDefault: true
  secureJsonData:
    password: 'logging'
  jsonData:
    sslmode: 'disable'
    postgresVersion: 903
    maxOpenConns: 5
  version: 1
  editable: true