apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring.prometheus  # Sets Deployment name
  namespace: default
  labels:
    app: prometheus
    project: monitoring
resources:
  - ./base/deployment.yml
  - ./base/service.yml
  - ./base/pv.yml
  - ./base/pvc.yml
  - ./base/ingress.yml
  - ./base/resource-monitoring.yml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: monitoring.prometheus
      labelSelector: "app=prometheus,project=monitoring"
    path: ./patch/deployment.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: monitoring-prometheus-ingress
    path: ./patch/ingress.yml
