apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus-volume
  labels:
    label: local
    app: monitoring-prometheus
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/monitoring-prometheus-data/prometheus.yml
