apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.alert-manager.config-claim # Sets name of PV
  labels:
    app: alert-manager
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany # Sets read and write access
  resources:
    requests:
      storage: 1Mi # Sets volume size
  volumeName: monitoring.alert-manager.config-volume
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.alert-manager.data-claim # Sets name of PV
  labels:
    app: alert-manager
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size
  volumeName: monitoring.alert-manager.data-volume
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.alert-manager.telegram-bot-token-claim # Sets name of PV
  labels:
    app: alert-manager
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany # Sets read and write access
  resources:
    requests:
      storage: 1Mi # Sets volume size
  volumeName: monitoring.alert-manager.telegram-bot-token-volume

