{
 "title": "Container Resource",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Project",
    "label": "project",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   },
   {
    "name": "Service",
    "label": "service",
    "query": {
     "query": "container_cpu_usage_seconds_total{project=~\"$Project\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{project=~\"$Project\", service=~\"$Service\"}[$__rate_interval]) * 100)"
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "device_temperature / 1000" }
   ]
  },
  {
   "title": "Total Memory Usage (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{project=~\"$Project\", service=~\"$Service\"}) / (1024^2)"
    }
   ]
  },
  {
   "title": "Container Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Health - last seen from now",
     "type": "stat",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - max(container_last_seen{project=~\"$Project\", service=~\"$Service\"}) by (name,project,service)",
       "legendFormat": "{{project}}-{{service}}"
      }
     ]
    }
   ]
  },
  { "title": "Container Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{project=~\"$Project\", service=~\"$Service\"}[$__rate_interval]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{project=~\"$Project\", service=~\"$Service\"}) / (1024^2)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}