apiVersion: v1
kind: Secret
metadata:
  name: monitoring.prometheus.api-user-secret
  labels:
    app: prometheus
    project: monitoring
  annotations:
    kubernetes.io/service-account.name: monitoring.prometheus.api-user
type: kubernetes.io/service-account-token
