apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.prometheus.config-volume
  labels:
    label: local
    app: prometheus
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/monitoring-prometheus-data/prometheus.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.prometheus.data-volume
  labels:
    label: local
    app: prometheus
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/monitoring-prometheus-data/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.prometheus.rule-volume
  labels:
    label: local
    app: prometheus
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/monitoring-prometheus-data/rules

