apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring.prometheus.api-user
  labels:
    app: prometheus
    project: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring.prometheus.api-user-secret
  labels:
    app: prometheus
    project: monitoring
  annotations:
    kubernetes.io/service-account.name: monitoring.prometheus.api-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring.prometheus.admin-api-user
  labels:
    app: prometheus
    project: monitoring
subjects:
- kind: ServiceAccount
  name: monitoring.prometheus.api-user
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
