apiVersion: v1
kind: Service
metadata:
  name: monitoring-jaeger-service # Sets service name
  labels:
    app: jaeger
    project: monitoring
spec:
  ports:
    - protocol: TCP
      port: 16686 # Sets port to run the postgres application
      targetPort: 16686
      name: jaeger-16686
    - protocol: TCP
      port: 14268
      targetPort: 14268
      name: jaeger-14268
  selector:
    app: jaeger
    project: monitoring
