apiVersion: v1
kind: Service
metadata:
  name: monitoring-jaeger-service # Sets service name
  labels:
    app: jaeger
    project: monitoring
spec:
  ports:
    - protocol: TCP
      port: 16686 # Sets port to run the postgres application
      targetPort: 16686
  selector:
    app: jaeger
    project: monitoring
