# data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.data-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/data
---
# dashboard
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.dashboard-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/dashboards
---
# provisioning
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.provisioning-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/provisioning
---
# ini
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.grafana.ini-volume
  labels:
    label: local
    app: grafana
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-grafana-data/grafana.ini
