# storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring.loki.storage-volume
  labels:
    label: local
    app: loki
    project: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/monitoring-loki-data/storage

