# storage
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: monitoring.loki.storage-claim # Sets name of PV
  labels:
    app: loki
    project: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size
  volumeName: monitoring.loki.storage-volume

