apiVersion: v1
kind: Service
metadata:
  name: monitoring-loki-service # Sets service name
  labels:
    app: loki
    project: monitoring
spec:
  ports:
    - protocol: TCP
      port: 3100 # Sets port to run the postgres application
      targetPort: 3100
      name: loki-3100
  selector:
    app: loki
    project: monitoring
